// flow-typed signature: 188d83ac94e9c18f0dd5e8bfb532901b
// flow-typed version: <<STUB>>/agenda_v1.0.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'agenda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'agenda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'agenda/lib/agenda/cancel' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/create' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/database' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/db-init' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/default-concurrency' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/default-lock-lifetime' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/default-lock-limit' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/define' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/every' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/find-and-lock-next-job' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/index' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/jobs' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/locklimit' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/max-concurrency' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/mongo' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/name' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/now' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/process-every' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/purge' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/save-job' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/schedule' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/sort' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/start' {
  declare module.exports: any;
}

declare module 'agenda/lib/agenda/stop' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/compute-next-run-at' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/disable' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/enable' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/fail' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/index' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/is-running' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/priority' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/remove' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/repeat-at' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/repeat-every' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/run' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/save' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/schedule' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/to-json' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/touch' {
  declare module.exports: any;
}

declare module 'agenda/lib/job/unique' {
  declare module.exports: any;
}

declare module 'agenda/lib/utils/create-job' {
  declare module.exports: any;
}

declare module 'agenda/lib/utils/index' {
  declare module.exports: any;
}

declare module 'agenda/lib/utils/process-jobs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'agenda/index' {
  declare module.exports: $Exports<'agenda'>;
}
declare module 'agenda/index.js' {
  declare module.exports: $Exports<'agenda'>;
}
declare module 'agenda/lib/agenda/cancel.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/cancel'>;
}
declare module 'agenda/lib/agenda/create.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/create'>;
}
declare module 'agenda/lib/agenda/database.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/database'>;
}
declare module 'agenda/lib/agenda/db-init.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/db-init'>;
}
declare module 'agenda/lib/agenda/default-concurrency.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/default-concurrency'>;
}
declare module 'agenda/lib/agenda/default-lock-lifetime.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/default-lock-lifetime'>;
}
declare module 'agenda/lib/agenda/default-lock-limit.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/default-lock-limit'>;
}
declare module 'agenda/lib/agenda/define.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/define'>;
}
declare module 'agenda/lib/agenda/every.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/every'>;
}
declare module 'agenda/lib/agenda/find-and-lock-next-job.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/find-and-lock-next-job'>;
}
declare module 'agenda/lib/agenda/index.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/index'>;
}
declare module 'agenda/lib/agenda/jobs.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/jobs'>;
}
declare module 'agenda/lib/agenda/locklimit.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/locklimit'>;
}
declare module 'agenda/lib/agenda/max-concurrency.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/max-concurrency'>;
}
declare module 'agenda/lib/agenda/mongo.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/mongo'>;
}
declare module 'agenda/lib/agenda/name.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/name'>;
}
declare module 'agenda/lib/agenda/now.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/now'>;
}
declare module 'agenda/lib/agenda/process-every.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/process-every'>;
}
declare module 'agenda/lib/agenda/purge.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/purge'>;
}
declare module 'agenda/lib/agenda/save-job.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/save-job'>;
}
declare module 'agenda/lib/agenda/schedule.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/schedule'>;
}
declare module 'agenda/lib/agenda/sort.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/sort'>;
}
declare module 'agenda/lib/agenda/start.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/start'>;
}
declare module 'agenda/lib/agenda/stop.js' {
  declare module.exports: $Exports<'agenda/lib/agenda/stop'>;
}
declare module 'agenda/lib/job/compute-next-run-at.js' {
  declare module.exports: $Exports<'agenda/lib/job/compute-next-run-at'>;
}
declare module 'agenda/lib/job/disable.js' {
  declare module.exports: $Exports<'agenda/lib/job/disable'>;
}
declare module 'agenda/lib/job/enable.js' {
  declare module.exports: $Exports<'agenda/lib/job/enable'>;
}
declare module 'agenda/lib/job/fail.js' {
  declare module.exports: $Exports<'agenda/lib/job/fail'>;
}
declare module 'agenda/lib/job/index.js' {
  declare module.exports: $Exports<'agenda/lib/job/index'>;
}
declare module 'agenda/lib/job/is-running.js' {
  declare module.exports: $Exports<'agenda/lib/job/is-running'>;
}
declare module 'agenda/lib/job/priority.js' {
  declare module.exports: $Exports<'agenda/lib/job/priority'>;
}
declare module 'agenda/lib/job/remove.js' {
  declare module.exports: $Exports<'agenda/lib/job/remove'>;
}
declare module 'agenda/lib/job/repeat-at.js' {
  declare module.exports: $Exports<'agenda/lib/job/repeat-at'>;
}
declare module 'agenda/lib/job/repeat-every.js' {
  declare module.exports: $Exports<'agenda/lib/job/repeat-every'>;
}
declare module 'agenda/lib/job/run.js' {
  declare module.exports: $Exports<'agenda/lib/job/run'>;
}
declare module 'agenda/lib/job/save.js' {
  declare module.exports: $Exports<'agenda/lib/job/save'>;
}
declare module 'agenda/lib/job/schedule.js' {
  declare module.exports: $Exports<'agenda/lib/job/schedule'>;
}
declare module 'agenda/lib/job/to-json.js' {
  declare module.exports: $Exports<'agenda/lib/job/to-json'>;
}
declare module 'agenda/lib/job/touch.js' {
  declare module.exports: $Exports<'agenda/lib/job/touch'>;
}
declare module 'agenda/lib/job/unique.js' {
  declare module.exports: $Exports<'agenda/lib/job/unique'>;
}
declare module 'agenda/lib/utils/create-job.js' {
  declare module.exports: $Exports<'agenda/lib/utils/create-job'>;
}
declare module 'agenda/lib/utils/index.js' {
  declare module.exports: $Exports<'agenda/lib/utils/index'>;
}
declare module 'agenda/lib/utils/process-jobs.js' {
  declare module.exports: $Exports<'agenda/lib/utils/process-jobs'>;
}
