// flow-typed signature: 7a4c9d60b45131544fba775905d882ab
// flow-typed version: <<STUB>>/getstream-node_v1.5.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'getstream-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'getstream-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'getstream-node/bin/run-tests' {
  declare module.exports: any;
}

declare module 'getstream-node/getstream' {
  declare module.exports: any;
}

declare module 'getstream-node/src/backends/activity' {
  declare module.exports: any;
}

declare module 'getstream-node/src/backends/base' {
  declare module.exports: any;
}

declare module 'getstream-node/src/backends/mongoose' {
  declare module.exports: any;
}

declare module 'getstream-node/src/backends/waterline' {
  declare module.exports: any;
}

declare module 'getstream-node/src/config.default' {
  declare module.exports: any;
}

declare module 'getstream-node/src/config' {
  declare module.exports: any;
}

declare module 'getstream-node/src/FeedManager' {
  declare module.exports: any;
}

declare module 'getstream-node/src/index' {
  declare module.exports: any;
}

declare module 'getstream-node/test/backend_activity_test' {
  declare module.exports: any;
}

declare module 'getstream-node/test/backends/base_test' {
  declare module.exports: any;
}

declare module 'getstream-node/test/backends/mongoose_test' {
  declare module.exports: any;
}

declare module 'getstream-node/test/backends/waterline_test' {
  declare module.exports: any;
}

declare module 'getstream-node/test/feed_manager_test' {
  declare module.exports: any;
}

declare module 'getstream-node/test/index_test' {
  declare module.exports: any;
}

declare module 'getstream-node/test/utils/promise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'getstream-node/bin/run-tests.js' {
  declare module.exports: $Exports<'getstream-node/bin/run-tests'>;
}
declare module 'getstream-node/getstream.js' {
  declare module.exports: $Exports<'getstream-node/getstream'>;
}
declare module 'getstream-node/src/backends/activity.js' {
  declare module.exports: $Exports<'getstream-node/src/backends/activity'>;
}
declare module 'getstream-node/src/backends/base.js' {
  declare module.exports: $Exports<'getstream-node/src/backends/base'>;
}
declare module 'getstream-node/src/backends/mongoose.js' {
  declare module.exports: $Exports<'getstream-node/src/backends/mongoose'>;
}
declare module 'getstream-node/src/backends/waterline.js' {
  declare module.exports: $Exports<'getstream-node/src/backends/waterline'>;
}
declare module 'getstream-node/src/config.default.js' {
  declare module.exports: $Exports<'getstream-node/src/config.default'>;
}
declare module 'getstream-node/src/config.js' {
  declare module.exports: $Exports<'getstream-node/src/config'>;
}
declare module 'getstream-node/src/FeedManager.js' {
  declare module.exports: $Exports<'getstream-node/src/FeedManager'>;
}
declare module 'getstream-node/src/index.js' {
  declare module.exports: $Exports<'getstream-node/src/index'>;
}
declare module 'getstream-node/test/backend_activity_test.js' {
  declare module.exports: $Exports<'getstream-node/test/backend_activity_test'>;
}
declare module 'getstream-node/test/backends/base_test.js' {
  declare module.exports: $Exports<'getstream-node/test/backends/base_test'>;
}
declare module 'getstream-node/test/backends/mongoose_test.js' {
  declare module.exports: $Exports<'getstream-node/test/backends/mongoose_test'>;
}
declare module 'getstream-node/test/backends/waterline_test.js' {
  declare module.exports: $Exports<'getstream-node/test/backends/waterline_test'>;
}
declare module 'getstream-node/test/feed_manager_test.js' {
  declare module.exports: $Exports<'getstream-node/test/feed_manager_test'>;
}
declare module 'getstream-node/test/index_test.js' {
  declare module.exports: $Exports<'getstream-node/test/index_test'>;
}
declare module 'getstream-node/test/utils/promise.js' {
  declare module.exports: $Exports<'getstream-node/test/utils/promise'>;
}
