// flow-typed signature: f351b500ef72536507dd33dc070c48b9
// flow-typed version: <<STUB>>/image-downloader_vfalse3.4.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'image-downloader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'image-downloader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'image-downloader/index' {
  declare module.exports: $Exports<'image-downloader'>;
}
declare module 'image-downloader/index.js' {
  declare module.exports: $Exports<'image-downloader'>;
}
