// flow-typed signature: e0211299ad383b511664f469325c4e7d
// flow-typed version: <<STUB>>/multer-sharp_v0.5.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multer-sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multer-sharp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multer-sharp/config/default' {
  declare module.exports: any;
}

declare module 'multer-sharp/lib/get-destination' {
  declare module.exports: any;
}

declare module 'multer-sharp/lib/get-filename' {
  declare module.exports: any;
}

declare module 'multer-sharp/lib/get-format' {
  declare module.exports: any;
}

declare module 'multer-sharp/lib/get-sharp-options' {
  declare module.exports: any;
}

declare module 'multer-sharp/lib/logger' {
  declare module.exports: any;
}

declare module 'multer-sharp/lib/transformer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multer-sharp/config/default.js' {
  declare module.exports: $Exports<'multer-sharp/config/default'>;
}
declare module 'multer-sharp/index' {
  declare module.exports: $Exports<'multer-sharp'>;
}
declare module 'multer-sharp/index.js' {
  declare module.exports: $Exports<'multer-sharp'>;
}
declare module 'multer-sharp/lib/get-destination.js' {
  declare module.exports: $Exports<'multer-sharp/lib/get-destination'>;
}
declare module 'multer-sharp/lib/get-filename.js' {
  declare module.exports: $Exports<'multer-sharp/lib/get-filename'>;
}
declare module 'multer-sharp/lib/get-format.js' {
  declare module.exports: $Exports<'multer-sharp/lib/get-format'>;
}
declare module 'multer-sharp/lib/get-sharp-options.js' {
  declare module.exports: $Exports<'multer-sharp/lib/get-sharp-options'>;
}
declare module 'multer-sharp/lib/logger.js' {
  declare module.exports: $Exports<'multer-sharp/lib/logger'>;
}
declare module 'multer-sharp/lib/transformer.js' {
  declare module.exports: $Exports<'multer-sharp/lib/transformer'>;
}
