// flow-typed signature: 3c3a8a0e9de1e0acaef8ae55529f2f51
// flow-typed version: <<STUB>>/node-mailjet_v^3.2.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-mailjet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-mailjet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-mailjet/examples/callback' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/contact' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/sender' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/sendmail/app' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/sendmail/button' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/sendmail/mailjetController' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/sendmail/public/javascripts/jquery' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/sendmail/public/javascripts/script' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/sendmail/routes/index' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/sendmail/routes/users' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/sendmail/test' {
  declare module.exports: any;
}

declare module 'node-mailjet/examples/user' {
  declare module.exports: any;
}

declare module 'node-mailjet/mailjet-client' {
  declare module.exports: any;
}

declare module 'node-mailjet/send' {
  declare module.exports: any;
}

declare module 'node-mailjet/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-mailjet/examples/callback.js' {
  declare module.exports: $Exports<'node-mailjet/examples/callback'>;
}
declare module 'node-mailjet/examples/contact.js' {
  declare module.exports: $Exports<'node-mailjet/examples/contact'>;
}
declare module 'node-mailjet/examples/sender.js' {
  declare module.exports: $Exports<'node-mailjet/examples/sender'>;
}
declare module 'node-mailjet/examples/sendmail/app.js' {
  declare module.exports: $Exports<'node-mailjet/examples/sendmail/app'>;
}
declare module 'node-mailjet/examples/sendmail/button.js' {
  declare module.exports: $Exports<'node-mailjet/examples/sendmail/button'>;
}
declare module 'node-mailjet/examples/sendmail/mailjetController.js' {
  declare module.exports: $Exports<'node-mailjet/examples/sendmail/mailjetController'>;
}
declare module 'node-mailjet/examples/sendmail/public/javascripts/jquery.js' {
  declare module.exports: $Exports<'node-mailjet/examples/sendmail/public/javascripts/jquery'>;
}
declare module 'node-mailjet/examples/sendmail/public/javascripts/script.js' {
  declare module.exports: $Exports<'node-mailjet/examples/sendmail/public/javascripts/script'>;
}
declare module 'node-mailjet/examples/sendmail/routes/index.js' {
  declare module.exports: $Exports<'node-mailjet/examples/sendmail/routes/index'>;
}
declare module 'node-mailjet/examples/sendmail/routes/users.js' {
  declare module.exports: $Exports<'node-mailjet/examples/sendmail/routes/users'>;
}
declare module 'node-mailjet/examples/sendmail/test.js' {
  declare module.exports: $Exports<'node-mailjet/examples/sendmail/test'>;
}
declare module 'node-mailjet/examples/user.js' {
  declare module.exports: $Exports<'node-mailjet/examples/user'>;
}
declare module 'node-mailjet/index' {
  declare module.exports: $Exports<'node-mailjet'>;
}
declare module 'node-mailjet/index.js' {
  declare module.exports: $Exports<'node-mailjet'>;
}
declare module 'node-mailjet/mailjet-client.js' {
  declare module.exports: $Exports<'node-mailjet/mailjet-client'>;
}
declare module 'node-mailjet/send.js' {
  declare module.exports: $Exports<'node-mailjet/send'>;
}
declare module 'node-mailjet/test/test.js' {
  declare module.exports: $Exports<'node-mailjet/test/test'>;
}
