// flow-typed signature: 2d77f2f8ed16232a7180f606e2cf7785
// flow-typed version: <<STUB>>/pusher-chatkit-server_v0.11.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pusher-chatkit-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pusher-chatkit-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pusher-chatkit-server/target/chatkit' {
  declare module.exports: any;
}

declare module 'pusher-chatkit-server/target/index' {
  declare module.exports: any;
}

declare module 'pusher-chatkit-server/target/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pusher-chatkit-server/target/chatkit.js' {
  declare module.exports: $Exports<'pusher-chatkit-server/target/chatkit'>;
}
declare module 'pusher-chatkit-server/target/index.js' {
  declare module.exports: $Exports<'pusher-chatkit-server/target/index'>;
}
declare module 'pusher-chatkit-server/target/utils.js' {
  declare module.exports: $Exports<'pusher-chatkit-server/target/utils'>;
}
