// @flow

export default class Shipping {
  // static;
}

export const buyerNeedsToPay = {
  data: {
    id: '9B27M6E',
    externalId: null,
    cartId: 574,
    productTitle: 'Кобзар 1846р',
    productPrice: 10000,
    productWeight: 1500,
    handlerPrice: 3500,
    status: 'NEW',
    reasonStep: null,
    buyerFirstName: 'Ґіанфранцо',
    buyerLastName: 'Палумбо',
    buyerPatronymic: '',
    buyerPhone: '380977414301',
    buyerEmail: 'gianpa+buyer@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+seller@gmail.com',
    lg: 'uk',
    createdAt: '2018-10-18T15:28:13.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '7b422fbe-e1b8-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta_ONOVA',
    },
    productPayment: {
      id: 617,
      amount: 10000,
      commissionAmount: 1600,
      status: 'NEW',
      statusCode: 'NEEDS_CONFIRMATION',
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: 'CONFIRMATION',
      details: {
        confirmation: {
          type: '3DS',
          url: 'https://acs.privatbank.ua/pPaReqMC.jsp',
          form: {
            PaReq:
              'eJxVUttu2zAMfc5fGP0A6xbLSqAKyJaHBZjTrHUf+lQYDpG4bRxXsre2Xz9SToJUgGCSh6R8DmnLvQdYPkA9eHC2gBCqHSTN9vZms7iH92eRqZnJ9XRmtMpu3MTGsJtM7F/woTm2TqQ8lZadXUS6qnWZ0CbPcqWV4lrJ3DKKIliAr/dV26M9sVX9/mO1dpnUMy0sO7mEHMCvlo6PR44fzBjDlNBWB3AlhD45d0zKKvxu2tfEsghSVn0c2t5/OsOnlp0dAgb/5vZ9380ZEzJHCjwVc4WHFZsVu4fQHdsAG3+sUZKm3aUvobOMqrCYXZGwm4HsML730WxdUT5+3ZU7tX75k90tn77W5eJfsYz31jLKoMxt1YOTXBiBNxFmLs1cGMtiPGpzoN91guuUc9RmdAnp6MXFBSb0OhR5D95DW3+6mUH04hEEH0gNMA+HdrGJ1BUR+/PXaT51j3rjCLMc9VdTTUOKsVOrBvWUkqvYq4niWkbV2C9uCokVlwqtb8v2H1mwumk=',
          },
          redirectUrl:
            'https://api.escrowbox.stage.uapay.ua/api/payments/617/confirmations',
        },
      },
      payReceipt:
        'https://api.stage.uapay.ua/api/receipts/b6789f1b-6d74-4691-b908-f65370b9b1b9.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 616,
      amount: 3500,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'ECOM',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.stage.uapay.ua/api/acquiring/receipts/escrowbox/9e9846af-1dbc-4b00-b0a7-686d1a299351.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const buyerPaidDeal = {
  data: {
    id: '9B27M6E',
    externalId: null,
    cartId: 599,
    productTitle: 'Кобзар 1846р',
    productPrice: 10000,
    productWeight: 1500,
    handlerPrice: 3500,
    status: 'PAID',
    reasonStep: null,
    buyerFirstName: 'Ґіанфранцо',
    buyerLastName: 'Палумбо',
    buyerPatronymic: '',
    buyerPhone: '380977414301',
    buyerEmail: 'gianpa+buyer@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+seller@gmail.com',
    lg: 'uk',
    createdAt: '2018-10-22T10:49:06.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '7b422fbe-e1b8-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta_ONOVA',
    },
    productPayment: {
      id: 1297,
      amount: 10000,
      commissionAmount: 1600,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: {
        confirmation: {
          type: '3DS',
          url: 'https://acs.privatbank.ua/pPaReqMC.jsp',
          form: {
            PaReq:
              'eJxVUttOwzAMfd5fVHxAc+ttUxZpsAcm0WlAeUZVZ7ECy0rSAvt77HSbRqSoto/t9BxbVzsHsHyGZnBgdAne128Qtdv5zWbxBF+vIk245KlKRSKTGzPRIWwmE/0NzrcHa0TMY6nZ2UWkq61JRVbkaa4ypXimZK4ZRREswTW72vZoT3TdfN2u1iaV2TQTmp1cQvbgVkvDxyPHD2aMYUqw9R5MBb6Pzh2jqvYPrf2INAsgZTWHwfbuaAqeaHZ2CBjcp9n1fTdjTMgcKfBYzBQeVm5W7Al8d7AeNu7QoCStfYvffacZVWExuyKhNwPZfnzvt92asnrh5XL1s65KUVaPx/Vy8VOOd64ZZVDmtu7BSC4KwaWMhJol05lAhiEetNnT7xrBs5hz1GZ0CenoxcUFJvQ6FHgPzoFtjmZaIHrxCIJfpAaYh0O72ETqioi+uz/Np+lRb8VzIWWukrSgIYXYqVWLekrJVejVBnE1o2rsFzaFxApLhda/ZfsDipm53Q==',
          },
          redirectUrl:
            'https://api.escrowbox.stage.uapay.ua/api/payments/1297/confirmations',
        },
      },
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/8cd4c37a-1278-44b8-8aa6-fe9fe07321ad.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 1296,
      amount: 3500,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'ECOM_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/1bfcb646-700c-498f-ae38-531105411d1f.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const sellerConfirmedResponse = {
  data: {
    id: 'KEYT6LM',
    externalId: null,
    cartId: 624,
    productTitle: "I don't know if you",
    productPrice: 11111,
    productWeight: 3000,
    handlerPrice: 2100,
    status: 'CONFIRMED',
    reasonStep: null,
    buyerFirstName: 'Пшфтакфс',
    buyerLastName: 'Зфдгьіщ',
    buyerPatronymic: '',
    buyerPhone: '380987987987',
    buyerEmail: 'gianpa+test@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+test3@gmail.com',
    lg: 'uk',
    createdAt: '2018-10-23T09:17:07.000Z',
    adId: null,
    handler: {
      status: 'CREATED',
      statusCode: null,
      statusText: null,
      waybillNumber: 20600000076896,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: 'Київ',
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: 'Відділення №1: вул. Червонопрапорна, 34 (Корчувате)',
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: 'Київ',
      recipientOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      recipientOfficeName:
        'Відділення №1: вул. Червонопрапорна, 34 (Корчувате)',
      type: 'NovaPoshta_ONOVA',
    },
    productPayment: {
      id: 1343,
      amount: 11111,
      commissionAmount: 1667,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: {
        confirmation: {
          type: '3DS',
          url: 'https://acs.privatbank.ua/pPaReqMC.jsp',
          form: {
            PaReq:
              'eJxVUttuwjAMfeYvKj6gudHLUBaJjYdVWhFi7HmqijXKRuiSdoN9/ewUEIsU1T7HdnJOo9dbBzB/gbp3YHQJ3lfvEDWb+/FytoKvN5FMuMxTqSTnk7EZ6QCb0Uh/g/PNwRoR81hqdkmRaStrEpHmWZKpVCmeKplpRiiSJbh6W9kO45Gu6q+HYmESmd6lQrNzSsweXDE3fFhy+GDFAFOBrfZg1uC76DIxWlf+ubEfkWaBpKr60NvOnUzOJ5pdEiJ692m2XddOGRMyQwk8FlOFi5XLgq3AtwfrYekONVrS2Pd451vNqAub2Y0Ivewp9sN5x2ZjyvUrL+fFZLErfsvd7Gcxn/2Uw77XjCqoclN1YCQXueBSRUJORTYV6GPAgzd7uq4RIosl4ueUmJZOnF1pYm+hoLt3Dmx9Mnc5R+GXjCg4ojTAOmy7xiTqRoh+fDr/n7pDvxXPZJ7wXCR0kQE7j2rQTym5CrOaYK5m1I3zwkshs8KjwujfY/sDsLK6AQ==',
          },
          redirectUrl:
            'https://api.escrowbox.stage.uapay.ua/api/payments/1343/confirmations',
        },
      },
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/6fb9874e-1825-47b8-9c36-85347e29f0db.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 1342,
      amount: 2100,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'ECOM_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/ebb46493-53b5-4496-a795-98bf8644a088.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const sellerCancelsAPaidDeal = {
  data: {
    id: 'ZS585UF',
    externalId: null,
    cartId: 639,
    productTitle: "I don't know if you",
    productPrice: 11111,
    productWeight: 3000,
    handlerPrice: 2100,
    status: 'PAID',
    reasonStep: null,
    buyerFirstName: 'Пшфтакфс',
    buyerLastName: 'Зфдгьіщ',
    buyerPatronymic: '',
    buyerPhone: '380987987987',
    buyerEmail: 'gianpa+test@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+test3@gmail.com',
    lg: 'uk',
    createdAt: '2018-10-24T14:16:56.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta_ONOVA',
    },
    productPayment: {
      id: 1373,
      amount: 11111,
      commissionAmount: 1667,
      status: 'REVERSED',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: {
        confirmation: {
          type: '3DS',
          url: 'https://acs.privatbank.ua/pPaReqMC.jsp',
          form: {
            PaReq:
              'eJxVUttOwzAMfd5fVHxAc1svm0KkQR+YRNAE2wNPqOosVmBZSVpgfD12dtGIWsX2sZ2cE+vlxgNUT9AMHoy2EEL9Ckm7vr5azB7h80VkY64mPJc8m6grM9IxbEYj/QU+tDtnRMpTqdnJRaSrnclEXhZZoXKleK5koRlFEbTgm03terRHum4+b+YPJpP5JBeaHV1CtuDnleGHJQ8bZhzClODqLZglhD45dUyWdbhv3XuiWQQpq9kNrvd7U/KxZieHgMF/mE3fd1PGhCyQAk/FVOFidjFnjxC6nQuw8LsGJWnda/oWOs2oCovZBQm9GMgOh/N+2rWxyxW3lc1s9by31Sqzv7NvW8X/WjPKoMx13YORXJSCy3Eiiil+nGsW41GbLV3XCFGkEvU9uoR0dOLsDBN6GYq8B+/BNXszKbHn2SMIfpAaYB6WnW0idUFE394d36fpUW/Fi0zSRcuCHinGjq1a1FNKrmKvNoqrGVVjvzgpJFYcKrT+Ddsfk3G53g==',
          },
          redirectUrl:
            'https://api.escrowbox.stage.uapay.ua/api/payments/1373/confirmations',
        },
      },
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/8732b397-45e8-4051-b24c-06dd802c4f94.pdf',
      reverseReceipt:
        'https://api.demo.uapay.ua/api/receipts/f607bf95-669c-49f6-95c8-9c7b5c745025.pdf',
      finishReceipt: null,
    },
    handlerPayment: {
      id: 1372,
      amount: 2100,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'ECOM_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/2955de75-7398-4c33-9cf7-222726457e56.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const dealConfirmationResp = {
  data: {
    id: 'E3319FS',
    externalId: null,
  },
};

export const buyerPaymentFailure = {
  data: {
    id: 'Z8QK927',
    externalId: null,
    cartId: 791,
    productTitle: "I don't know if you",
    productPrice: 11111,
    productWeight: 3000,
    handlerPrice: 3500,
    status: 'NEW',
    reasonStep: null,
    buyerFirstName: 'Тим',
    buyerLastName: 'Пррп',
    buyerPatronymic: '',
    buyerPhone: '380987987987',
    buyerEmail: 'gianpa+test@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+test3@gmail.com',
    lg: 'uk',
    createdAt: '2018-11-01T15:36:03.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '511fcf97-e1c2-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta_ONOVA',
    },
    productPayment: {
      id: 1678,
      amount: 11111,
      commissionAmount: 1667,
      status: 'REJECTED',
      statusCode: 'REJECTED',
      statusText:
        '{"code":"AUTHENTICATION_ERROR","message":"Internal server error","responseCode":"074","source":"TAS_P2P"}',
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/27a30371-a07d-4991-9d8f-a7f3c94e8edb.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 1677,
      amount: 3500,
      commissionAmount: 0,
      status: 'REJECTED',
      statusCode: 'REJECTED',
      statusText:
        '{"code":"INVALID_CREDENTIAL","message":"Unable to authenticate","pluginId":"1","responseCode":"074","source":"TAS_ECOM"}',
      type: 'ECOM_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/887db946-6623-42a1-b91d-6229f0aeda80.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const novaPoshta = {
  // 1 - Tracking number generated. Waiting for seller to ship package.
  //
  // @SELLER please ship the item ASAP.
  notShipped: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '29-10-2018 21:24:51',
        DocumentWeight: 5,
        CheckWeight: 0,
        DocumentCost: 73,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: '',
        CounterpartyType: '',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 0,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        WarehouseRecipientInternetAddressRef: '',
        MarketplacePartnerToken: '',
        DateScan: '0001-01-01 00:00:00',
        PaymentStatus: 'PREAUTH',
        PaymentStatusDate: '29.10.2018 21:25:56',
        AmountToPay: 73,
        AmountPaid: 0,
        InternationalDeliveryType: '',
        UndeliveryReasonsDate: '',
        RecipientWarehouseTypeRef: '',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        OwnerDocumentNumber: '',
        Status: 'Нова пошта очікує надходження від відправника',
        StatusCode: '1',
        RefEW: '00000000-0000-0000-0000-000000000000',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        SenderAddress: '',
        RecipientAddress: '',
        AnnouncedPrice: '',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // 6 - Seller left the package. Ready to depart towards <city> - Estimated arrival time: XXX
  //
  // Item has been shipped. It should arrive on XXX
  shipped: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '31-10-2018 17:13:22',
        DocumentWeight: 5,
        CheckWeight: 0,
        DocumentCost: 73,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        MarketplacePartnerToken: '***REMOVED***',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        DateScan: '17:17 30.10.2018',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        InternationalDeliveryType: '',
        AnnouncedPrice: '',
        OwnerDocumentNumber: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        Status:
          'Відправлення у місті Львів. Очікуйте повідомлення про прибуття',
        StatusCode: '6',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // 41 - Preparing package to be shipped towards <city>
  preparedForDeparture: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '31-10-2018 17:13:22',
        DocumentWeight: 5,
        CheckWeight: 0,
        DocumentCost: 73,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseSender: 'Відділення №14 (до 30 кг): вул. Словацького, 5',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        DateScan: '21:35 30.10.2018',
        MarketplacePartnerToken: '***REMOVED***',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        LastAmountTransferGM: '',
        LastAmountReceivedCommissionGM: '',
        InternationalDeliveryType: '',
        UndeliveryReasonsDate: '',
        AnnouncedPrice: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        OwnerDocumentNumber: '',
        Status: 'Готується до відправлення у місті Львів',
        StatusCode: '41',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // 6 - Package in transit towards <city>
  onItsWay: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '31-10-2018 17:13:22',
        DocumentWeight: 5,
        CheckWeight: 0,
        DocumentCost: 73,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        MarketplacePartnerToken: '***REMOVED***',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        DateScan: '22:43 30.10.2018',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        InternationalDeliveryType: '',
        AnnouncedPrice: '',
        OwnerDocumentNumber: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        Status:
          'Відправлення у місті Львів. Очікуйте повідомлення про прибуття',
        StatusCode: '6',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // 7 - Package arrived at office.
  //
  // @BUYER please colect the item ASAP.
  delivered: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '31-10-2018 17:13:22',
        DocumentWeight: 5,
        CheckWeight: 0,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        MarketplacePartnerToken: '***REMOVED***',
        DateScan: '10:24 31.10.2018',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        DocumentCost: 73,
        AnnouncedPrice: '',
        OwnerDocumentNumber: '',
        DateFirstDayStorage: '2018-11-06',
        DateReturnCargo: '',
        InternationalDeliveryType: '',
        DaysStorageCargo: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        StorageAmount: '',
        StoragePrice: '',
        Status: 'Прибув у відділення',
        StatusCode: '7',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '2018-11-06 00:00:00',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // 9 -
  collected: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        OwnerDocumentType: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        DateCreated: '31-10-2018 17:13:22',
        CheckWeight: 0,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '31.10.2018 16:52:04',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        MarketplacePartnerToken: '***REMOVED***',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        DateScan: '0001-01-01 00:00:00',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        LastAmountTransferGM: '',
        LastAmountReceivedCommissionGM: '',
        DocumentCost: 73,
        DocumentWeight: 5,
        AnnouncedPrice: '',
        UndeliveryReasonsDate: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        OwnerDocumentNumber: '',
        InternationalDeliveryType: '',
        WarehouseSender: 'Відділення №14 (до 30 кг): вул. Словацького, 5',
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        LoyaltyCardSender: '',
        LoyaltyCardRecipient: '9e221cd6-43ba-11e8-aa3a-0025b501a04b',
        Status: 'Відправлення отримано',
        StatusCode: '9',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },
};
